# Generated by Django 5.1.6 on 2025-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('jobs', 'Jobs'), ('services', 'Services'), ('business', 'Business'), ('vehicles', 'Vehicles')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
