# Generated by Django 5.1.6 on 2025-03-04 05:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_category_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_3'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_4'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_5'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_6'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_main'),
        ),
    ]
