# Generated by Django 5.1.6 on 2025-03-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_lot_size_alter_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
