# Generated by Django 5.1.6 on 2025-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
