# Generated by Django 5.1.6 on 2025-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
