# Generated by Django 5.1.6 on 2025-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tag',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
